### ISSUE TITLE
Hi, code is fantastic!

### ISSUE THREAD

**Issue by burhanbarakli** [PKU-ICST-MIPL/DRLIH_TMM2020#3]
But, in your train.py code;
traintest=Dataloader("c:/Users/bb/Desktop/DRLIH_TMM2020-main/cifar10/train",0,500,0,10)
You use 500 images for traning, but in next_training.py your parameter 5500 and in cifar10 every  category has 5000 images.

Another topic is, i ran your train.py and which py files should I run **respectively**. In my opinion next-train.py and extract.py? Am i right?

Thank you.

**Comment by magicfisk** [comment]
> 

Thanks for your attention!

There are 60,000 images in Cifar10. Thus, 500 images of every category are used for training and the rest 5,500 images of every category are used for the test. 

next-train.py is only the code to continue training, which is not necessary. After running the train.py, you can use extract.py to get the hash codes for the test.

**Comment by burhanbarakli** [comment]
> > 
> 
> Thanks for your attention!
> 
> There are 60,000 images in Cifar10. Thus, 500 images of every category are used for training and the rest 5,500 images of every category are used for the test.
> 
> next-train.py is only the code to continue training, which is not necessary. After running the train.py, you can use extract.py to get the hash codes for the test.

thank you for reply!
